name: Build Extension

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Extension
        run: |
          chmod +x gradlew
          ./gradlew make
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Crunchyroll Extension
          path: build/*.cs3
